import { StyleSheet } from 'react-native';

// アプリ全体で共有する StyleSheet。
// 最小分割フェーズでは App.tsx の StyleSheet をそのまま集約している。
// 将来的には theme（色・余白）と画面別スタイルへ分割する余地がある。
export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#101419',
  },
  flex: {
    flex: 1,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  header: {
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  appName: {
    color: '#f4f7fb',
    fontSize: 25,
    fontWeight: '800',
  },
  headerSub: {
    color: '#a7b0bd',
    marginTop: 4,
    fontSize: 12,
  },
  badge: {
    backgroundColor: '#243d3b',
    borderColor: '#37c9a5',
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  badgeText: {
    color: '#8af2d1',
    fontWeight: '700',
  },
  tabs: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    gap: 8,
    paddingBottom: 10,
  },
  tab: {
    flex: 1,
    minHeight: 42,
    borderRadius: 8,
    backgroundColor: '#1a2028',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#2a3340',
  },
  activeTab: {
    backgroundColor: '#263748',
    borderColor: '#61a8ff',
  },
  tabText: {
    color: '#aeb7c4',
    fontWeight: '700',
  },
  activeTabText: {
    color: '#f4f7fb',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 14,
    paddingBottom: 40,
  },
  stack: {
    gap: 12,
  },
  title: {
    color: '#f4f7fb',
    fontSize: 24,
    fontWeight: '800',
  },
  pageTitle: {
    color: '#f4f7fb',
    fontSize: 22,
    fontWeight: '800',
  },
  hero: {
    backgroundColor: '#18222e',
    borderColor: '#2f6d79',
    borderWidth: 1,
    borderRadius: 8,
    padding: 18,
  },
  heroTitle: {
    color: '#f4f7fb',
    fontSize: 24,
    fontWeight: '800',
  },
  heroText: {
    color: '#b7c3d1',
    marginTop: 8,
    lineHeight: 20,
  },
  panel: {
    backgroundColor: '#171d25',
    borderColor: '#2c3643',
    borderWidth: 1,
    borderRadius: 8,
    padding: 14,
    gap: 12,
  },
  panelText: {
    color: '#dce5ef',
    lineHeight: 20,
  },
  sectionTitle: {
    color: '#f4f7fb',
    fontSize: 18,
    fontWeight: '800',
  },
  exerciseTitle: {
    color: '#f4f7fb',
    fontSize: 17,
    fontWeight: '800',
  },
  muted: {
    color: '#9aa6b5',
    lineHeight: 19,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    alignItems: 'center',
  },
  metricGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metric: {
    minWidth: '22%',
    flexGrow: 1,
    backgroundColor: '#101820',
    borderColor: '#2b3644',
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
  },
  metricValue: {
    color: '#f4f7fb',
    fontSize: 18,
    fontWeight: '800',
  },
  metricLabel: {
    color: '#8f9cab',
    marginTop: 3,
    fontSize: 12,
  },
  primaryButton: {
    backgroundColor: '#2d7df0',
    minHeight: 46,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    marginTop: 10,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontWeight: '800',
  },
  secondaryButton: {
    backgroundColor: '#244135',
    minHeight: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#40c987',
  },
  secondaryButtonText: {
    color: '#94f1bd',
    fontWeight: '800',
  },
  smallButton: {
    backgroundColor: '#2d7df0',
    minHeight: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  smallButtonText: {
    color: '#fff',
    fontWeight: '800',
  },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  exerciseChip: {
    width: '48%',
    minHeight: 58,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#354254',
    backgroundColor: '#111922',
    padding: 10,
    justifyContent: 'center',
  },
  exerciseChipText: {
    color: '#f4f7fb',
    fontWeight: '800',
  },
  exerciseChipSub: {
    color: '#8f9cab',
    marginTop: 4,
    fontSize: 12,
  },
  staticChip: {
    backgroundColor: '#22303e',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  staticChipText: {
    color: '#dce5ef',
    fontWeight: '700',
  },
  setCard: {
    backgroundColor: '#101820',
    borderColor: '#2b3644',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    gap: 10,
  },
  completedSetCard: {
    borderColor: '#3b7b68',
  },
  setTitle: {
    color: '#f4f7fb',
    fontWeight: '800',
  },
  setActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pill: {
    borderColor: '#3a4656',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  activePill: {
    backgroundColor: '#4b3c18',
    borderColor: '#f5c048',
  },
  pillText: {
    color: '#aeb7c4',
    fontWeight: '800',
  },
  activePillText: {
    color: '#ffe09b',
  },
  deleteButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  deleteButtonText: {
    color: '#ff8a8a',
    fontWeight: '800',
  },
  inputGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  numberField: {
    width: '48%',
    backgroundColor: '#171f29',
    borderRadius: 8,
    borderColor: '#2d3847',
    borderWidth: 1,
    padding: 9,
  },
  inputLabel: {
    color: '#8f9cab',
    fontSize: 12,
    fontWeight: '700',
  },
  numberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  numberInput: {
    color: '#f4f7fb',
    fontSize: 18,
    fontWeight: '800',
    minHeight: 34,
    flex: 1,
    padding: 0,
    textAlign: 'center',
  },
  stepButton: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#263748',
  },
  stepButtonText: {
    color: '#f4f7fb',
    fontWeight: '900',
    fontSize: 16,
  },
  suffix: {
    color: '#8f9cab',
    fontWeight: '700',
  },
  memoInput: {
    color: '#f4f7fb',
    minHeight: 42,
    backgroundColor: '#171f29',
    borderRadius: 8,
    borderColor: '#2d3847',
    borderWidth: 1,
    paddingHorizontal: 10,
  },
  textInput: {
    color: '#f4f7fb',
    minHeight: 46,
    backgroundColor: '#101820',
    borderRadius: 8,
    borderColor: '#2d3847',
    borderWidth: 1,
    paddingHorizontal: 12,
  },
  timerButton: {
    backgroundColor: '#4d3d17',
    minHeight: 38,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#dba233',
  },
  doneButton: {
    backgroundColor: '#214238',
    borderColor: '#49d19a',
  },
  timerButtonText: {
    color: '#fff0c7',
    fontWeight: '800',
  },
  timerBanner: {
    marginHorizontal: 14,
    marginBottom: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dba233',
    backgroundColor: '#2a2519',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  timerFinished: {
    borderColor: '#49d19a',
    backgroundColor: '#162820',
  },
  timerLabel: {
    color: '#9aa6b5',
    fontSize: 12,
    fontWeight: '800',
  },
  timerTitle: {
    color: '#f4f7fb',
    fontWeight: '800',
    marginTop: 2,
  },
  timerTime: {
    color: '#f4f7fb',
    fontSize: 24,
    fontWeight: '900',
  },
  timerActions: {
    flexDirection: 'row',
    gap: 6,
  },
  iconButton: {
    borderColor: '#465466',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  iconButtonText: {
    color: '#dce5ef',
    fontWeight: '800',
    fontSize: 12,
  },
  historyItem: {
    borderTopColor: '#2b3644',
    borderTopWidth: 1,
    paddingTop: 10,
    gap: 4,
  },
  historyTitle: {
    color: '#f4f7fb',
    fontWeight: '800',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ghostButton: {
    minHeight: 40,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#3a4656',
    backgroundColor: '#1a2230',
  },
  ghostButtonText: {
    color: '#cdd6e3',
    fontWeight: '800',
  },
  restRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#101820',
    borderColor: '#2b3644',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  restValue: {
    color: '#ffe09b',
    fontWeight: '800',
    fontSize: 16,
  },
  dangerButton: {
    minHeight: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#7a2f33',
    backgroundColor: '#2a1618',
  },
  dangerButtonText: {
    color: '#ff8a8a',
    fontWeight: '800',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(6, 9, 13, 0.72)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#171d25',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderColor: '#2c3643',
    borderWidth: 1,
    padding: 18,
    gap: 12,
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  picker: {
    flex: 1,
    color: '#f4f7fb',
  },
  pickerItem: {
    color: '#f4f7fb',
    fontSize: 22,
  },
  pickerUnit: {
    color: '#aeb7c4',
    fontWeight: '800',
    fontSize: 16,
  },
  primaryButtonFlat: {
    backgroundColor: '#2d7df0',
    minHeight: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
});
